### ISSUE TITLE
Доступ к заданиям

### ISSUE THREAD

**Issue by Cliffart44** [zinka22/Selenium-cource#10]
<details><summary>README.md</summary>
<p>

https://github.com/zinka22/Selenium-cource/blob/3c2e97321ce9b1c0e1af5ef8dc7327e2344aecd3/README.md?plain=1#L1-L22

</p>
</details> 

Было бы хорошо привести в порядок `README.md` — сейчас от ссылок на задания толку мало, так как нормально они не открываются.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/zinka22/Selenium-cource/assets/64852774/0c6d4d88-ef92-4cb2-a1c9-dec87a319002)

</p>
</details> 

Поэтому, возможно, задания стоит целиком разместить в этом файле, либо решить эту проблему каким-то ещё способом. И было бы хорошо сделать это до #9.

**Comment by Cliffart44** [comment]
@zinka22, кстати, ещё [это](https://habr.com/ru/companies/yandex_praktikum/articles/812139/) может быть полезным.

**Comment by zinka22** [comment]
прочитала, добавила в notion. Завтра еще почитаю, повторю.

пока вижу два варианта привести в порядок README.MD:
1) перенести название файла репозитория, скрин его задачи, ссылку на его задачу в стороннее хранилище (notion с доступом по ссылке или google doc с доступом по ссылке). В README.MD писать название задачи и ссылку на notion/goodleDoc
2) в пару к ветке main сделать ветку tasks. Каждую новую задачу цеплять веткой  от tasks, описывать условие в и скрин в описании к pull request.

Старым задачам в таком случае дополнить описание в README.MD в виде ссылки на картинку со скрином по задаче.

**Comment by Cliffart44** [comment]
> пока вижу два варианта привести в порядок README.MD:
> 
> 1. перенести название файла репозитория, скрин его задачи, ссылку на его задачу в стороннее хранилище (notion с доступом по ссылке или google doc с доступом по ссылке). В README.MD писать название задачи и ссылку на notion/goodleDoc
> 2. в пару к ветке main сделать ветку tasks. Каждую новую задачу цеплять веткой  от tasks, описывать условие в и скрин в описании к pull request.
> 
> Старым задачам в таком случае дополнить описание в README.MD в виде ссылки на картинку со скрином по задаче.

Судя по всему, GitHub позволит всё разместить непосредственно в нём. А раз это возможно, то будет хорошо так и сделать.

Тогда вместо создания документов Notion/Google Docs можно в текущем репозитории создавать отдельные md-файлы с заданиями и на py-файлы прикладывать [относительные ссылки](https://github.blog/2013-01-31-relative-links-in-markup-files/) в таких md-файлах. Что касается пункта 2 — вместо отдельной ветки лучше создать отдельный каталог для таких md-файлов. Весь необходимый код и документация к нему в таком случае будут в основной ветке.

Для начала можешь сделать pull request с одним коммитом и одним добавленным md-фалом (скажем, для #9). Посмотрим, как выглядит, и если 🆗, тогда остальные можно будет оформить в том же духе.

**Comment by zinka22** [comment]
попробовала, не получается.
Завтра попробую еще раз, ничего смотреть не нужно

**Comment by Cliffart44** [comment]
> Для начала можешь сделать pull request с одним коммитом и одним добавленным md-фалом



> попробовала, не получается. Завтра попробую еще раз, ничего смотреть не нужно

Как говорил ранее https://github.com/zinka22/Selenium-cource/issues/10#issuecomment-2110509908, лучше сделать pull pequest с одним коммитом и одним добавленным md-фалом, а не смешивать изменения с уже имеющимися pull request-ами. И снова затем связать его с этой Issue, как в https://github.com/zinka22/Selenium-cource/issues/3#issue-2261117859.

**Comment by Cliffart44** [comment]
> (скажем, для #9)

Не обязательно для него, можно для любого другого задания. Просто тут было бы 2 в 1: и #9 можно было бы слить, и пример документации получить.
