### ISSUE TITLE
Заполнение таблицы упражнений в README.md

### ISSUE THREAD

**Issue by Cliffart44** [zinka22/Selenium-cource#15]
По мотивам #11 {и https://github.com/zinka22/Selenium-cource/pull/11#pullrequestreview-2075573876 } стоит добавить описания к остальным уже имеющимся упражнениям, причём, поэтапно: для каждого задания нужен  отдельный pull request. Таким образом строки вне таблицы будут "переезжать" вовнутрь таблицы.

![Screenshot_20240526-200634~2.png](https://github.com/zinka22/Selenium-cource/assets/64852774/cb892b87-a471-4857-8e22-03946fdf89fd)

__P.S.__ Также посмотри, не будет ли удобно `py`-файлы реализаций тоже собрать в папку.

**Comment by zinka22** [comment]
> Также посмотри, не будет ли удобно `py`-файлы реализаций тоже собрать в папку.

перенесла в отдельную папку, в рамках #15
