### ISSUE TITLE
Изменение наименования элемента х

### ISSUE THREAD

**Issue by zinka22** [zinka22/Selenium-cource#19]
В рамках задачи требуется:
1) найти все задачи, для решения которых использован результат вычисления математического выражения
2) изменить название переменной, в которую попадает значение х (значение, которое подставляем для вычисления выражения)

**Comment by Cliffart44** [comment]
Источник: https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615260480.

**Comment by zinka22** [comment]
в рамках задачи нужно:
1) изменить именование переменной с x, element_x_int
2) перенести логику преобразования в int в функцию solve_math_expression_for_captcha
