### ISSUE TITLE
Перенос дополнительной логики в функцию solve_math_expression_for_captcha, helpers.py

### ISSUE THREAD

**Issue by zinka22** [zinka22/Selenium-cource#20]
В рамках данной задачи нужно:
1) перенести логику перевода элемента х в int в функцию solve_math_expression_for_captcha (дополнить имеющуюся);
2) убрать логику перевода в int из решения задач.

**Comment by Cliffart44** [comment]
Источник: https://github.com/zinka22/Selenium-cource/pull/13#discussion_r1615260480.

**Comment by Cliffart44** [comment]
@zinka22, и ещё добавь, пожалуйста, это в строке объявления функции:
```python
...int) -> str:
```
