### ISSUE TITLE
Имя класса

### ISSUE THREAD

**Issue by Cliffart44** [zinka22/Selenium-cource#27]
Что означает имя класса? Почему выбрано именно такое?
https://github.com/zinka22/Selenium-cource/blob/487b1873fc41b83ad119cac38876e241d1d682c0/solutions/unittest_style.py#L11

**Comment by zinka22** [comment]
тут название класса - TestAbs - не обозначает ничего.
Списала с предваряющей задачу теории.

Откуда списала
<details><summary>фото 1</summary>
<p>

![image](https://github.com/zinka22/Selenium-cource/assets/108293161/7c3e874d-fc8e-49c9-94b9-a6986d3152d2)

</p>
</details>
что в задаче
<details><summary>фото 2</summary>
<p>

![image](https://github.com/zinka22/Selenium-cource/assets/108293161/6342566c-53a8-46df-b4d6-6a0f5fa54c0b)

</p>
</details>

За последние пару дней напомнила себе, как наследуется класс: тут можно было переименовать на более осмысленное имя. 
_____________________________
итого: имя класса не было выбрано, название взято с примера кода из теории.

**Comment by Cliffart44** [comment]
@zinka22, тогда давай исправим на что-то осмысленное 🙂
